### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by fabiosalvi** [giusepperossetti/angTrial#1]
@giusepperossetti 

Scaffolding is the subdivision of a project into folders, **properly handled.**

This app's scaffolding is out of phase.

All the stuff in "appAng" should go in "angTrial".

Notice that currently you have two README.md in different folders. WTF?!? :-)

**Comment by giusepperossetti** [comment]
Here's the thing:
when you run
`ng new {name of the app}`
angular generates a new folder. So I created the repo first and then generated the app inside of the repo folder.

**Comment by fabiosalvi** [comment]
@giusepperossetti 

Aaaaaaaand

 **THAT**'s

 why back in the days I told you to establish a C:\Git folder and then to start from there.

Supposing your app name is "myApp" then your workflow should be:

1 ) Go to Github and create a repo called "myApp"

2 ) Go to your /Git folder and from there
```
git clone blablabla/myApp.git
``` 

3 ) Stay in /Git

4a) If you are using React you launch:
```
create-react-app myApp

cd myApp

git add .
git commit -m "Initial commit"
git push
``` 
In this way you have obtained a merging of Github files (.gitignore and stuff) with the basic scaffolding from the app creator, and all the stuff is in the righe place in your repo.

4b) If you are using Angular you launch:
```
ng new myApp

cd myApp

git add .
git commit -m "Initial commit"
git push
``` 
And so the story goes!
