### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by fabiosalvi** [giusepperossetti/angTrial#2]
@giusepperossetti 
README.md is verbose.

You don't need to write "Dependencies da installare per l'utilizzo di questa app: " and the rest,
because it's implicit in your package.json.

You just need to tell him

1) Install Angular, (and you put the commmand there)

2) Run npm install (and you put the command there)

3) Run the server (and you put the command there)

Take inspiration from this mini repo:
https://github.com/fabiosalvi/loginlogout

Then take inspiration from the repos of stuff you have used (like ng-bootstrap)
and then build from there.

**Comment by giusepperossetti** [comment]
Done. Closing the issue.
